packages:
  - issuer+verifier
  - aws
  - server/aws/src
  - server/aws/resources
  - google-cloud
  - docusaurus
  - server/multi
  - server/single
  - server/core
  - server/google-cloud
allowBuilds:
  '@firebase/util': true
  core-js: true
  core-js-pure: true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-kms'
  - '@aws-sdk/credential-provider-ini@3.973.4'
  - '@aws-sdk/credential-provider-login@3.972.66'
  - '@aws-sdk/credential-provider-node@3.972.70'
