packages:
  - issuer+verifier
  - aws
  - server/aws/src
  - server/aws/resources
  - google-cloud
  - docusaurus
  - server/multi
  - server/single
  - server/core
  - server/google-cloud
allowBuilds:
  '@firebase/util': true
  core-js: true
  core-js-pure: true
  esbuild: true
  protobufjs: true
