export type ErrorCodes =
  // OAuth 2.0 :: Token Error Response
  //
  // https://www.rfc-editor.org/rfc/rfc6749.html#section-5.2
  // https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-6.3
  | 'INVALID_REQUEST'
  | 'INVALID_CLIENT'
  | 'INVALID_GRANT'
  | 'UNAUTHORIZED_CLIENT'
  | 'UNSUPPORTED_GRANT_TYPE'
  | 'INVALID_SCOPE'

  // OID4VCI :: Credential Error Response
  //
  // https://www.rfc-editor.org/rfc/rfc6750.html#section-3.1
  // https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#section-7.3.1
  | 'INVALID_TOKEN'
  | 'INSUFFICIENT_SCOPE'
  | 'INVALID_CREDENTIAL_REQUEST'
  | 'UNSUPPORTED_CREDENTIAL_TYPE'
  | 'UNSUPPORTED_CREDENTIAL_FORMAT'
  | 'INVALID_PROOF'
  | 'INVALID_ENCRYPTION_PARAMETERS'
  | 'CREDENTIAL_REQUEST_DENIED'
  | 'UNSUPPORTED_CREDENTIAL_TYPE'

  // OID4VP :: Error Response
  //
  // https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-6.4
  | 'ACCESS_DENIED'
  | 'VP_FORMATS_NOT_SUPPORTED'
  | 'INVALID_PRESENTATION_DEFINITION_URI'
  | 'INVALID_PRESENTATION_DEFINITION_REFERENCE'
  | 'INVALID_REQUEST_URI_METHOD'
  | 'WALLET_UNAVAILABLE'

  // VCKNOTS :: CLIENT ERROR
  | 'ISSUER_NOT_FOUND'
  | 'VERIFIER_NOT_FOUND'
  | 'CREDENTIAL_CONFIGURATION_NOT_FOUND'
  | 'AUTHORIZATION_METADATA_NOT_FOUND'
  | 'OFFER_NOT_FOUND'
  | 'PRE_AUTHORIZED_CODE_NOT_FOUND'
  | 'DUPLICATE_CREDENTIAL_CONFIGURATION_NAME'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'USER_NOT_FOUND'
  | 'ISSUER_USER_ALREADY_EXISTS'
  | 'VERIFIER_USER_ALREADY_EXISTS'
  | 'JWKS_NOT_FOUND'
  | 'INVALID_PRESENTATION_SUBMISSION'
  | 'INVALID_OPTIONS'

  // VCKNOTS :: SERVER ERROR
  | 'INTERNAL_SERVER_ERROR'
  | 'ILLEGAL_ARGUMENT'
  | 'ILLEGAL_STATE'
  | 'FEATURE_NOT_IMPLEMENTED_YET'
  | 'PROVIDER_NOT_FOUND'
  | 'ISSUER_PUBLIC_KEY_CORRUPTED'
  | 'ISSUER_ASYMMETRIC_SIGN_FAILED'
  | 'UNSUPPORTED_ISSUER_KEY_ALG'
  | 'INVALID_ACCESS_TOKEN'
  | 'AUTHZ_ISSUER_KEY_NOT_FOUND'
  | 'AUTHZ_VERIFIER_KEY_NOT_FOUND'
  | 'INVALID_NONCE'
  | 'INVALID_CREDENTIAL'
  | 'INVALID_PROOF'
  | 'UNSUPPORTED_VP_TOKEN'
  | 'INVALID_VP_TOKEN'
  | 'INVALID_JWT'
  | 'INVALID_CLAIMS'
  | 'INTERNAL_SERVER_ERROR'
  | 'HOLDER_BINDING_FAILED'
  | 'UNSUPPORTED_CLIENT_ID_SCHEME'
  | 'INVALID_CERTIFICATE'
  | 'DUPLICATE_VERIFIER'
  | 'DUPLICATE_ISSUER'
  | 'DUPLICATE_AUTHZ_SERVER'
  | 'CERTIFICATE_NOT_FOUND'
  | 'REQUEST_OBJECT_NOT_FOUND'
  | 'VERIFIER_VP_FORMATS_NOT_SUPPORTED'
