name: CI docs deploy(on merge to main)

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "docusaurus/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.18.1
          cache: npm
          cache-dependency-path: ./docusaurus/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./docusaurus

      - name: Build Docusaurus
        run: npm run build
        working-directory: ./docusaurus

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docusaurus/build
          publish_branch: gh-pages
