name: CI docs check build(on PR changed)

on:
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
      - "docusaurus/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6.0.10

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm


      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter docusaurus build
